// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/jtyers/tmaas-api-util/combo"
	"github.com/jtyers/tmaas-api-util/errors"
	extractor2 "github.com/jtyers/tmaas-api-util/firebase/extractor"
	"github.com/jtyers/tmaas-api-util/serviceaccount/extractor"
	"github.com/jtyers/tmaas-cors-config"
	"github.com/jtyers/tmaas-model/validator"
	"github.com/jtyers/tmaas-service-dao/datastore"
	"github.com/jtyers/tmaas-service-util/id"
	"github.com/jtyers/tmaas-service-util/idchecker"
	"github.com/jtyers/tmaas-service-util/requestor"
	"github.com/jtyers/tmaas-threat-api/client"
	"github.com/jtyers/tmaas-threat-model-api/dao"
	"github.com/jtyers/tmaas-threat-model-api/service"
	"github.com/jtyers/tmaas-threat-model-api/web"
	"net/http"
)

// Injectors from wire.go:

func InitialiseRouter() (http.Handler, error) {
	context := datastore.NewContext()
	datastoreConfiguration := dao.NewDatastoreConfig()
	datastoreClient, err := datastore.NewDatastoreClient(context, datastoreConfiguration)
	if err != nil {
		return nil, err
	}
	randomIDProviderPrefix := dao.NewThreatModelRandomIDProviderPrefix()
	defaultRandomIDProvider := id.NewDefaultRandomIDProvider(randomIDProviderPrefix)
	threatModelIDCreator := dao.NewThreatModelIDCreator()
	threatModelDao, err := dao.NewThreatModelDao(datastoreClient, defaultRandomIDProvider, datastoreConfiguration, threatModelIDCreator)
	if err != nil {
		return nil, err
	}
	defaultStructValidator, err := validator.NewDefaultStructValidator()
	if err != nil {
		return nil, err
	}
	defaultIDChecker := idchecker.NewDefaultIDChecker()
	threatServiceClientConfig := client.NewThreatServiceClientConfig()
	defaultRequestorWithContext := requestor.NewDefaultRequestorWithContext()
	threatServiceClient := client.NewThreatServiceClient(threatServiceClientConfig, defaultRequestorWithContext)
	defaultThreatModelService := service.NewDefaultThreatModelService(threatModelDao, defaultStructValidator, defaultIDChecker, threatServiceClient)
	threatModelHandlers := web.NewThreatModelHandlers(defaultThreatModelService)
	iamClient, err := extractor.NewIamClient(context)
	if err != nil {
		return nil, err
	}
	defaultVerifier := extractor.NewDefaultVerifier(iamClient)
	defaultExtractor := extractor.NewDefaultExtractor(defaultVerifier)
	app, err := extractor2.NewFirebaseApp(context)
	if err != nil {
		return nil, err
	}
	authClient, err := extractor2.NewFirebaseAuthClient(context, app)
	if err != nil {
		return nil, err
	}
	defaultFirebaseVerifier := extractor2.NewDefaultFirebaseVerifier(authClient)
	defaultFirebaseExtractor := extractor2.NewDefaultFirebaseExtractor(defaultFirebaseVerifier)
	serviceAccountPermissionsJson := combo.NewServiceAccountPermissionsJson()
	defaultComboMiddlewareFactory, err := combo.NewDefaultComboMiddlewareFactory(defaultExtractor, defaultFirebaseExtractor, serviceAccountPermissionsJson)
	if err != nil {
		return nil, err
	}
	defaultErrorsMiddlewareFactory := errors.NewDefaultErrorsMiddlewareFactory()
	corsMiddleware := corsconfig.FromEnv()
	handler := web.NewRouter(threatModelHandlers, defaultComboMiddlewareFactory, defaultErrorsMiddlewareFactory, corsMiddleware)
	return handler, nil
}
