// Code generated by MockGen. DO NOT EDIT.
// Source: control_dao.go

// Package dao is a generated GoMock package.
package dao

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/jtyers/tmaas-model"
)

// MockControlDao is a mock of ControlDao interface.
type MockControlDao struct {
	ctrl     *gomock.Controller
	recorder *MockControlDaoMockRecorder
}

// MockControlDaoMockRecorder is the mock recorder for MockControlDao.
type MockControlDaoMockRecorder struct {
	mock *MockControlDao
}

// NewMockControlDao creates a new mock instance.
func NewMockControlDao(ctrl *gomock.Controller) *MockControlDao {
	mock := &MockControlDao{ctrl: ctrl}
	mock.recorder = &MockControlDaoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockControlDao) EXPECT() *MockControlDaoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockControlDao) Create(ctx context.Context, data *model.Control) (*model.Control, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, data)
	ret0, _ := ret[0].(*model.Control)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockControlDaoMockRecorder) Create(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockControlDao)(nil).Create), ctx, data)
}

// Delete mocks base method.
func (m *MockControlDao) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockControlDaoMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockControlDao)(nil).Delete), ctx, id)
}

// DeleteWhere mocks base method.
func (m *MockControlDao) DeleteWhere(ctx context.Context, query *model.Control) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWhere", ctx, query)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWhere indicates an expected call of DeleteWhere.
func (mr *MockControlDaoMockRecorder) DeleteWhere(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWhere", reflect.TypeOf((*MockControlDao)(nil).DeleteWhere), ctx, query)
}

// Get mocks base method.
func (m *MockControlDao) Get(ctx context.Context, id string) (*model.Control, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*model.Control)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockControlDaoMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockControlDao)(nil).Get), ctx, id)
}

// GetAll mocks base method.
func (m *MockControlDao) GetAll(ctx context.Context) ([]*model.Control, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]*model.Control)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockControlDaoMockRecorder) GetAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockControlDao)(nil).GetAll), ctx)
}

// QueryExact mocks base method.
func (m *MockControlDao) QueryExact(ctx context.Context, query *model.Control) ([]*model.Control, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryExact", ctx, query)
	ret0, _ := ret[0].([]*model.Control)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryExact indicates an expected call of QueryExact.
func (mr *MockControlDaoMockRecorder) QueryExact(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryExact", reflect.TypeOf((*MockControlDao)(nil).QueryExact), ctx, query)
}

// QueryExactSingle mocks base method.
func (m *MockControlDao) QueryExactSingle(ctx context.Context, query *model.Control) (*model.Control, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryExactSingle", ctx, query)
	ret0, _ := ret[0].(*model.Control)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryExactSingle indicates an expected call of QueryExactSingle.
func (mr *MockControlDaoMockRecorder) QueryExactSingle(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryExactSingle", reflect.TypeOf((*MockControlDao)(nil).QueryExactSingle), ctx, query)
}

// UpdateWhereExact mocks base method.
func (m *MockControlDao) UpdateWhereExact(ctx context.Context, queryExact, data *model.Control) ([]*model.Control, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWhereExact", ctx, queryExact, data)
	ret0, _ := ret[0].([]*model.Control)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWhereExact indicates an expected call of UpdateWhereExact.
func (mr *MockControlDaoMockRecorder) UpdateWhereExact(ctx, queryExact, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWhereExact", reflect.TypeOf((*MockControlDao)(nil).UpdateWhereExact), ctx, queryExact, data)
}

// UpdateWhereExactSingle mocks base method.
func (m *MockControlDao) UpdateWhereExactSingle(ctx context.Context, queryExact, data *model.Control) (*model.Control, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWhereExactSingle", ctx, queryExact, data)
	ret0, _ := ret[0].(*model.Control)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWhereExactSingle indicates an expected call of UpdateWhereExactSingle.
func (mr *MockControlDaoMockRecorder) UpdateWhereExactSingle(ctx, queryExact, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWhereExactSingle", reflect.TypeOf((*MockControlDao)(nil).UpdateWhereExactSingle), ctx, queryExact, data)
}
