// Code generated by MockGen. DO NOT EDIT.
// Source: data_flow_diagram_dao.go

// Package dao is a generated GoMock package.
package dao

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entities "github.com/jtyers/tmaas-model"
)

// MockDataFlowDiagramDao is a mock of DataFlowDiagramDao interface.
type MockDataFlowDiagramDao struct {
	ctrl     *gomock.Controller
	recorder *MockDataFlowDiagramDaoMockRecorder
}

// MockDataFlowDiagramDaoMockRecorder is the mock recorder for MockDataFlowDiagramDao.
type MockDataFlowDiagramDaoMockRecorder struct {
	mock *MockDataFlowDiagramDao
}

// NewMockDataFlowDiagramDao creates a new mock instance.
func NewMockDataFlowDiagramDao(ctrl *gomock.Controller) *MockDataFlowDiagramDao {
	mock := &MockDataFlowDiagramDao{ctrl: ctrl}
	mock.recorder = &MockDataFlowDiagramDaoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataFlowDiagramDao) EXPECT() *MockDataFlowDiagramDaoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDataFlowDiagramDao) Create(ctx context.Context, data *entities.DataFlowDiagram) (*entities.DataFlowDiagram, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, data)
	ret0, _ := ret[0].(*entities.DataFlowDiagram)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDataFlowDiagramDaoMockRecorder) Create(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDataFlowDiagramDao)(nil).Create), ctx, data)
}

// Delete mocks base method.
func (m *MockDataFlowDiagramDao) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDataFlowDiagramDaoMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDataFlowDiagramDao)(nil).Delete), ctx, id)
}

// DeleteWhere mocks base method.
func (m *MockDataFlowDiagramDao) DeleteWhere(ctx context.Context, query *entities.DataFlowDiagram) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWhere", ctx, query)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWhere indicates an expected call of DeleteWhere.
func (mr *MockDataFlowDiagramDaoMockRecorder) DeleteWhere(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWhere", reflect.TypeOf((*MockDataFlowDiagramDao)(nil).DeleteWhere), ctx, query)
}

// Get mocks base method.
func (m *MockDataFlowDiagramDao) Get(ctx context.Context, id string) (*entities.DataFlowDiagram, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*entities.DataFlowDiagram)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDataFlowDiagramDaoMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDataFlowDiagramDao)(nil).Get), ctx, id)
}

// GetAll mocks base method.
func (m *MockDataFlowDiagramDao) GetAll(ctx context.Context) ([]*entities.DataFlowDiagram, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]*entities.DataFlowDiagram)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockDataFlowDiagramDaoMockRecorder) GetAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockDataFlowDiagramDao)(nil).GetAll), ctx)
}

// QueryExact mocks base method.
func (m *MockDataFlowDiagramDao) QueryExact(ctx context.Context, query *entities.DataFlowDiagram) ([]*entities.DataFlowDiagram, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryExact", ctx, query)
	ret0, _ := ret[0].([]*entities.DataFlowDiagram)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryExact indicates an expected call of QueryExact.
func (mr *MockDataFlowDiagramDaoMockRecorder) QueryExact(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryExact", reflect.TypeOf((*MockDataFlowDiagramDao)(nil).QueryExact), ctx, query)
}

// QueryExactSingle mocks base method.
func (m *MockDataFlowDiagramDao) QueryExactSingle(ctx context.Context, query *entities.DataFlowDiagram) (*entities.DataFlowDiagram, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryExactSingle", ctx, query)
	ret0, _ := ret[0].(*entities.DataFlowDiagram)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryExactSingle indicates an expected call of QueryExactSingle.
func (mr *MockDataFlowDiagramDaoMockRecorder) QueryExactSingle(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryExactSingle", reflect.TypeOf((*MockDataFlowDiagramDao)(nil).QueryExactSingle), ctx, query)
}

// UpdateWhereExact mocks base method.
func (m *MockDataFlowDiagramDao) UpdateWhereExact(ctx context.Context, queryExact, data *entities.DataFlowDiagram) ([]*entities.DataFlowDiagram, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWhereExact", ctx, queryExact, data)
	ret0, _ := ret[0].([]*entities.DataFlowDiagram)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWhereExact indicates an expected call of UpdateWhereExact.
func (mr *MockDataFlowDiagramDaoMockRecorder) UpdateWhereExact(ctx, queryExact, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWhereExact", reflect.TypeOf((*MockDataFlowDiagramDao)(nil).UpdateWhereExact), ctx, queryExact, data)
}

// UpdateWhereExactSingle mocks base method.
func (m *MockDataFlowDiagramDao) UpdateWhereExactSingle(ctx context.Context, queryExact, data *entities.DataFlowDiagram) (*entities.DataFlowDiagram, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWhereExactSingle", ctx, queryExact, data)
	ret0, _ := ret[0].(*entities.DataFlowDiagram)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWhereExactSingle indicates an expected call of UpdateWhereExactSingle.
func (mr *MockDataFlowDiagramDaoMockRecorder) UpdateWhereExactSingle(ctx, queryExact, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWhereExactSingle", reflect.TypeOf((*MockDataFlowDiagramDao)(nil).UpdateWhereExactSingle), ctx, queryExact, data)
}
