// Code generated by MockGen. DO NOT EDIT.
// Source: threat_dao.go

// Package dao is a generated GoMock package.
package dao

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entities "github.com/jtyers/tmaas-model"
)

// MockThreatDao is a mock of ThreatDao interface.
type MockThreatDao struct {
	ctrl     *gomock.Controller
	recorder *MockThreatDaoMockRecorder
}

// MockThreatDaoMockRecorder is the mock recorder for MockThreatDao.
type MockThreatDaoMockRecorder struct {
	mock *MockThreatDao
}

// NewMockThreatDao creates a new mock instance.
func NewMockThreatDao(ctrl *gomock.Controller) *MockThreatDao {
	mock := &MockThreatDao{ctrl: ctrl}
	mock.recorder = &MockThreatDaoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockThreatDao) EXPECT() *MockThreatDaoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockThreatDao) Create(ctx context.Context, data *entities.Threat) (*entities.Threat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, data)
	ret0, _ := ret[0].(*entities.Threat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockThreatDaoMockRecorder) Create(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockThreatDao)(nil).Create), ctx, data)
}

// Delete mocks base method.
func (m *MockThreatDao) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockThreatDaoMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockThreatDao)(nil).Delete), ctx, id)
}

// DeleteWhere mocks base method.
func (m *MockThreatDao) DeleteWhere(ctx context.Context, query *entities.Threat) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWhere", ctx, query)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWhere indicates an expected call of DeleteWhere.
func (mr *MockThreatDaoMockRecorder) DeleteWhere(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWhere", reflect.TypeOf((*MockThreatDao)(nil).DeleteWhere), ctx, query)
}

// Get mocks base method.
func (m *MockThreatDao) Get(ctx context.Context, id string) (*entities.Threat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*entities.Threat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockThreatDaoMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockThreatDao)(nil).Get), ctx, id)
}

// GetAll mocks base method.
func (m *MockThreatDao) GetAll(ctx context.Context) ([]*entities.Threat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]*entities.Threat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockThreatDaoMockRecorder) GetAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockThreatDao)(nil).GetAll), ctx)
}

// QueryExact mocks base method.
func (m *MockThreatDao) QueryExact(ctx context.Context, query *entities.Threat) ([]*entities.Threat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryExact", ctx, query)
	ret0, _ := ret[0].([]*entities.Threat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryExact indicates an expected call of QueryExact.
func (mr *MockThreatDaoMockRecorder) QueryExact(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryExact", reflect.TypeOf((*MockThreatDao)(nil).QueryExact), ctx, query)
}

// QueryExactSingle mocks base method.
func (m *MockThreatDao) QueryExactSingle(ctx context.Context, query *entities.Threat) (*entities.Threat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryExactSingle", ctx, query)
	ret0, _ := ret[0].(*entities.Threat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryExactSingle indicates an expected call of QueryExactSingle.
func (mr *MockThreatDaoMockRecorder) QueryExactSingle(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryExactSingle", reflect.TypeOf((*MockThreatDao)(nil).QueryExactSingle), ctx, query)
}

// UpdateWhereExact mocks base method.
func (m *MockThreatDao) UpdateWhereExact(ctx context.Context, queryExact, data *entities.Threat) ([]*entities.Threat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWhereExact", ctx, queryExact, data)
	ret0, _ := ret[0].([]*entities.Threat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWhereExact indicates an expected call of UpdateWhereExact.
func (mr *MockThreatDaoMockRecorder) UpdateWhereExact(ctx, queryExact, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWhereExact", reflect.TypeOf((*MockThreatDao)(nil).UpdateWhereExact), ctx, queryExact, data)
}

// UpdateWhereExactSingle mocks base method.
func (m *MockThreatDao) UpdateWhereExactSingle(ctx context.Context, queryExact, data *entities.Threat) (*entities.Threat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWhereExactSingle", ctx, queryExact, data)
	ret0, _ := ret[0].(*entities.Threat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWhereExactSingle indicates an expected call of UpdateWhereExactSingle.
func (mr *MockThreatDaoMockRecorder) UpdateWhereExactSingle(ctx, queryExact, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWhereExactSingle", reflect.TypeOf((*MockThreatDao)(nil).UpdateWhereExactSingle), ctx, queryExact, data)
}
