// Code generated by MockGen. DO NOT EDIT.
// Source: threat_model_service.go

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entities "github.com/jtyers/tmaas-model"
)

// MockThreatModelService is a mock of ThreatModelService interface.
type MockThreatModelService struct {
	ctrl     *gomock.Controller
	recorder *MockThreatModelServiceMockRecorder
}

// MockThreatModelServiceMockRecorder is the mock recorder for MockThreatModelService.
type MockThreatModelServiceMockRecorder struct {
	mock *MockThreatModelService
}

// NewMockThreatModelService creates a new mock instance.
func NewMockThreatModelService(ctrl *gomock.Controller) *MockThreatModelService {
	mock := &MockThreatModelService{ctrl: ctrl}
	mock.recorder = &MockThreatModelServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockThreatModelService) EXPECT() *MockThreatModelServiceMockRecorder {
	return m.recorder
}

// CreateThreatModel mocks base method.
func (m *MockThreatModelService) CreateThreatModel(ctx context.Context, threatModel entities.ThreatModel) (*entities.ThreatModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateThreatModel", ctx, threatModel)
	ret0, _ := ret[0].(*entities.ThreatModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateThreatModel indicates an expected call of CreateThreatModel.
func (mr *MockThreatModelServiceMockRecorder) CreateThreatModel(ctx, threatModel interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateThreatModel", reflect.TypeOf((*MockThreatModelService)(nil).CreateThreatModel), ctx, threatModel)
}

// GetThreatModel mocks base method.
func (m *MockThreatModelService) GetThreatModel(ctx context.Context, id entities.ThreatModelID) (*entities.ThreatModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThreatModel", ctx, id)
	ret0, _ := ret[0].(*entities.ThreatModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThreatModel indicates an expected call of GetThreatModel.
func (mr *MockThreatModelServiceMockRecorder) GetThreatModel(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThreatModel", reflect.TypeOf((*MockThreatModelService)(nil).GetThreatModel), ctx, id)
}

// GetThreatModels mocks base method.
func (m *MockThreatModelService) GetThreatModels(ctx context.Context) ([]*entities.Threat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThreatModels", ctx)
	ret0, _ := ret[0].([]*entities.Threat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThreatModels indicates an expected call of GetThreatModels.
func (mr *MockThreatModelServiceMockRecorder) GetThreatModels(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThreatModels", reflect.TypeOf((*MockThreatModelService)(nil).GetThreatModels), ctx)
}

// UpdateThreatModel mocks base method.
func (m *MockThreatModelService) UpdateThreatModel(ctx context.Context, threatModelID entities.ThreatModelID, threatModel entities.ThreatModel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateThreatModel", ctx, threatModelID, threatModel)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateThreatModel indicates an expected call of UpdateThreatModel.
func (mr *MockThreatModelServiceMockRecorder) UpdateThreatModel(ctx, threatModelID, threatModel interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateThreatModel", reflect.TypeOf((*MockThreatModelService)(nil).UpdateThreatModel), ctx, threatModelID, threatModel)
}
